#include "backtester.hpp"
#include "strategy.hpp"

#include <chrono>
#include <filesystem>

using namespace hft;

namespace {

void write_report(const EngineConfig& cfg, const Metrics& metrics,
                  const QuotePair& last_quote, double elapsed_seconds) {
    const std::filesystem::path path(cfg.report_path);
    if (path.has_parent_path()) std::filesystem::create_directories(path.parent_path());
    std::ofstream out(cfg.report_path);
    if (!out) throw std::runtime_error("cannot write report: " + cfg.report_path);

    out << "# Performance Report\n\n";
    out << "Generated by `build/backtester`.\n\n";
    out << "## Configuration\n\n";
    out << "- LOB file: `" << cfg.lob_path << "`\n";
    out << "- Processed snapshots: " << metrics.snapshots << "\n";
    out << "- Quote interval: " << cfg.quote_interval_events << " snapshots\n";
    out << "- Order quantity: " << cfg.order_quantity << "\n";
    out << "- Microprice extension: " << (cfg.use_microprice_extension ? "enabled" : "disabled") << "\n";
    out << "- Gamma: " << cfg.gamma << "\n";
    out << "- Kappa: " << cfg.kappa << "\n\n";
    out << "## Results\n\n";
    out << std::fixed << std::setprecision(10);
    out << "| Metric | Value |\n";
    out << "| --- | ---: |\n";
    out << "| Mark-to-market PnL | "       << metrics.mark_to_market_pnl() << " |\n";
    out << "| Cash | "                      << metrics.cash                 << " |\n";
    out << "| Inventory | "                 << metrics.inventory            << " |\n";
    out << "| Last mid | "                  << metrics.last_mid             << " |\n";
    out << "| Turnover | "                  << metrics.turnover             << " |\n";
    out << "| Fees | "                      << metrics.realized_fees        << " |\n";
    out << "| Fills | "                     << metrics.fills                << " |\n";
    out << "| Orders placed | "             << metrics.orders_placed        << " |\n";
    out << "| Cancels | "                   << metrics.cancels              << " |\n";
    out << "| Max abs inventory | "         << metrics.max_abs_inventory    << " |\n";
    out << "| Last reservation price | "    << last_quote.reservation_price << " |\n";
    out << "| Last half spread | "          << last_quote.half_spread       << " |\n";
    out << "| Last rolling volatility | "   << last_quote.volatility        << " |\n";
    out << "| Runtime seconds | "           << elapsed_seconds              << " |\n\n";
    out << "## Execution Assumption\n\n";
    out << "Resting buys fill when the replayed best ask is less than or equal to the order price. ";
    out << "Resting sells fill when the replayed best bid is greater than or equal to the order price. ";
    out << "Each fill executes the configured order quantity at the visible crossing price.\n";
}

}  // namespace

int main(int argc, char** argv) {
    try {
        const std::string config_path = argc > 1 ? argv[1] : "configs/default.conf";
        const EngineConfig cfg = load_config(config_path);
        validate_config(cfg);

        CsvBookReader reader(cfg.lob_path, cfg.levels);
        AvellanedaStoikovStrategy strategy(cfg);
        OrderManager orders;
        Metrics      metrics;
        BookSnapshot book;
        QuotePair    last_quote;

        reader.prepare(book); // pre-size asks/bids vectors once

        Fill fill_buf[MAX_FILLS_PER_TICK]; // stack buffer; no alloc in hot loop

        const auto start = std::chrono::steady_clock::now();
        while (reader.next(book)) {
            ++metrics.snapshots;
            metrics.last_mid = book.mid();
            strategy.observe(book);

            const auto n_fills = orders.match_crossing_orders(book, fill_buf, MAX_FILLS_PER_TICK);
            for (std::size_t i = 0; i < n_fills; ++i) {
                apply_fill(fill_buf[i], cfg.fee_bps, metrics);
            }

            if (metrics.snapshots > cfg.warmup_events &&
                metrics.snapshots % cfg.quote_interval_events == 0) {
                metrics.cancels += orders.cancel_all();
                last_quote = strategy.quote(book, metrics.inventory);
                if (metrics.inventory < cfg.inventory_limit) {
                    orders.place(Side::Buy, last_quote.bid, cfg.order_quantity, book.timestamp);
                    ++metrics.orders_placed;
                }
                if (metrics.inventory > -cfg.inventory_limit) {
                    orders.place(Side::Sell, last_quote.ask, cfg.order_quantity, book.timestamp);
                    ++metrics.orders_placed;
                }
            }

            if (cfg.max_events > 0 && metrics.snapshots >= cfg.max_events) break;
        }

        metrics.cancels += orders.cancel_all();
        const auto end     = std::chrono::steady_clock::now();
        const double elapsed = std::chrono::duration<double>(end - start).count();

        write_report(cfg, metrics, last_quote, elapsed);

        std::cout << std::fixed << std::setprecision(10);
        std::cout << "snapshots=" << metrics.snapshots
                  << " pnl="       << metrics.mark_to_market_pnl()
                  << " inventory=" << metrics.inventory
                  << " turnover="  << metrics.turnover
                  << " fills="     << metrics.fills
                  << " report="    << cfg.report_path << '\n';
    } catch (const std::exception& ex) {
        std::cerr << "error: " << ex.what() << '\n';
        return 1;
    }
    return 0;
}
